# docker-compose.yml
version: '3.8'

services:
  gin-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # ホストのカレントディレクトリをコンテナの /app にマウント
    command: ["air"]  # ファイル変更を監視して再ビルドするツール
